Feat/product page
Axepuff/fake-burrberry-frontend pull request #2
Opened 2017-08-02 22:43 UTC by Axepuff

2017-08-03 12:16 UTC, evgenyrodionov commented
Коммиты не по формату

2017-08-03 12:16 UTC, evgenyrodionov commented
зачем второй пр открыл?

2017-08-03 12:17 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28921471-c574c806-785e-11e7-95c5-41176687d407.png)
![image](https://user-images.githubusercontent.com/775692/28921481-cbf9bc04-785e-11e7-8717-7f2363a5be26.png)
![image](https://user-images.githubusercontent.com/775692/28921491-d6394806-785e-11e7-8f3a-5128b37b88b4.png)
![image](https://user-images.githubusercontent.com/775692/28921497-dc1811e4-785e-11e7-8b1f-b00da96fc8e6.png)

2017-08-04 09:02 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28961958-cee70738-790c-11e7-9890-2b2697a0c70a.png)
![image](https://user-images.githubusercontent.com/775692/28961968-d48d4d00-790c-11e7-992a-b63580823da3.png)

2017-08-04 09:07 UTC, imevro requested changes
- Сброс дефолтных стилей
- Суперфикс ширины или высоты картинок
- Стили на тегах
- нейминг слабый, хоть и видна какая-то систематизация
- кодстайл в хтмл в описании
- большая вложенность в галерее и инфо и вообще много где
- списки не для списков
- проблемы с описанием

2017-08-04 09:07 UTC, evgenyrodionov commented on css/master.css
> +  fon-size: 16px;
fon?

2017-08-04 09:07 UTC, evgenyrodionov commented on css/master.css
> +  background: #fff url("../image/logo.svg") no-repeat center;
логотип это пикча, поэтому нормально его нужно использовать

2017-08-04 09:07 UTC, evgenyrodionov commented on css/master.css
> +li:last-child .product-color-list_color{
задротский селектор

2017-08-04 09:07 UTC, evgenyrodionov commented on index.html
> +      <img src="image\logo.svg" alt="Burberry">
пути идут через "/"

2017-08-04 09:07 UTC, evgenyrodionov commented on index.html
> +      <img src="image\logo.svg" alt="Burberry">
image? там одна пикча будет храниться?

2017-08-04 15:17 UTC, Axepuff commented
Сделал меньше вложенность, глянул на нейминг и офигел – на работе другой кодстайл, и я все смешал в какой-то момент. Сделал получше.
Остальные моменты тоже пофиксил.
(Кстати вот реально мыло в футере на домашнем ноуте даже не видел)

2017-08-04 18:27 UTC, imevro requested changes

2017-08-04 18:27 UTC, evgenyrodionov commented on css/master.css
> +.product-color-list__item.black {
итем это плохой общий нейминг

2017-08-04 18:27 UTC, evgenyrodionov commented on css/master.css
> +.product-color-list__item.black {
классы типа .блэк слишком общие опять же

2017-08-04 20:49 UTC, Axepuff commented
Исправил имена классов, может не самое лучше название для ссылок "more for you", но имхо там явный список. Если не итем, то в голову приходит только враппер

2017-08-05 08:59 UTC, Axepuff commented
Блин, я случайно залил планшетную версию с фиксами по первому дз, а там ещё футер не готов (и вероятно ещё что-то).

2017-08-05 15:01 UTC, imevro requested changes

2017-08-05 15:01 UTC, evgenyrodionov commented on index.html
> +            <div class="col-xs-6 col-md-3"">
у тебя в конце закрывающая и открывающая кавычка

2017-08-05 15:01 UTC, evgenyrodionov commented on index.html
> +            <li class="more-list__link-wrapper"><a href="#" class="more-list__link">Men’s Black Trench Coats</a></li>
это не список

2017-08-05 19:11 UTC, evgenyrodionov commented on index.html
> +            <div class="col-xs-6 col-md-3"">
И?

2017-08-05 19:12 UTC, imevro requested changes

2017-08-05 19:12 UTC, evgenyrodionov commented on index.html
> +            <div class="col-xs-6 col-md-3"">
и? смысл игнорить мои комментарии?

2017-08-05 19:21 UTC, Axepuff commented
не запушил чёт

2017-08-06 07:46 UTC, imevro requested changes

2017-08-06 07:46 UTC, evgenyrodionov commented on index.html
> +                <ul class="delivery-feautures">
это не список

2017-08-06 07:51 UTC, evgenyrodionov commented
После этого делаешь мердж через сквош

2017-08-06 14:08 UTC, merged